# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bill_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(688, 527)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.input_veh = QtWidgets.QLineEdit(self.frame_3)
        self.input_veh.setObjectName("input_veh")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_veh)
        self.textEdit_desc = QtWidgets.QTextEdit(self.frame_3)
        self.textEdit_desc.setObjectName("textEdit_desc")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit_desc)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.input_date = QtWidgets.QLineEdit(self.frame_4)
        self.input_date.setObjectName("input_date")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_date)
        self.input_advisor = QtWidgets.QLineEdit(self.frame_4)
        self.input_advisor.setObjectName("input_advisor")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_advisor)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        self.frame_6 = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_7)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.input_qty = QtWidgets.QLineEdit(self.frame_7)
        self.input_qty.setObjectName("input_qty")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_qty)
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.input_part = QtWidgets.QLineEdit(self.frame_7)
        self.input_part.setObjectName("input_part")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_part)
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.bt_add = QtWidgets.QPushButton(self.frame_6)
        self.bt_add.setObjectName("bt_add")
        self.horizontalLayout_3.addWidget(self.bt_add)
        self.bt_delete = QtWidgets.QPushButton(self.frame_6)
        self.bt_delete.setObjectName("bt_delete")
        self.horizontalLayout_3.addWidget(self.bt_delete)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.parts_use_table = QtWidgets.QTableWidget(self.frame_2)
        self.parts_use_table.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.parts_use_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.parts_use_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.parts_use_table.setObjectName("parts_use_table")
        self.parts_use_table.setColumnCount(5)
        self.parts_use_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.parts_use_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.parts_use_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.parts_use_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.parts_use_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.parts_use_table.setHorizontalHeaderItem(4, item)
        self.parts_use_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.parts_use_table)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_5 = QtWidgets.QFrame(Dialog)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bt_bill = QtWidgets.QPushButton(self.frame_5)
        self.bt_bill.setObjectName("bt_bill")
        self.horizontalLayout_2.addWidget(self.bt_bill)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_2.raise_()
        self.frame_6.raise_()
        self.frame.raise_()
        self.frame_5.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Vehicle"))
        self.label_2.setText(_translate("Dialog", "Job Descrption"))
        self.label_3.setText(_translate("Dialog", "Date"))
        self.label_4.setText(_translate("Dialog", "Service Advisor"))
        self.label_10.setText(_translate("Dialog", "Part"))
        self.label_11.setText(_translate("Dialog", "Quantity"))
        self.bt_add.setText(_translate("Dialog", "Add"))
        self.bt_delete.setText(_translate("Dialog", "Delete"))
        item = self.parts_use_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Part ID"))
        item = self.parts_use_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Name"))
        item = self.parts_use_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Price"))
        item = self.parts_use_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Quantity"))
        item = self.parts_use_table.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Total"))
        self.bt_bill.setText(_translate("Dialog", "Generate Bill"))

