# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 's_add.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(753, 442)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.input_address = QtWidgets.QLineEdit(self.groupBox)
        self.input_address.setEnabled(False)
        self.input_address.setObjectName("input_address")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_address)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.input_contact = QtWidgets.QLineEdit(self.groupBox)
        self.input_contact.setEnabled(False)
        self.input_contact.setObjectName("input_contact")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_contact)
        self.input_c_name = QtWidgets.QLineEdit(self.groupBox)
        self.input_c_name.setClearButtonEnabled(True)
        self.input_c_name.setObjectName("input_c_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_c_name)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_reg_no = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_reg_no.setObjectName("comboBox_reg_no")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_reg_no)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.input_type = QtWidgets.QLineEdit(self.groupBox_2)
        self.input_type.setEnabled(False)
        self.input_type.setObjectName("input_type")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_type)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.input_model = QtWidgets.QLineEdit(self.groupBox_2)
        self.input_model.setEnabled(False)
        self.input_model.setObjectName("input_model")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_model)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.input_job_desc = QtWidgets.QTextEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_job_desc.sizePolicy().hasHeightForWidth())
        self.input_job_desc.setSizePolicy(sizePolicy)
        self.input_job_desc.setObjectName("input_job_desc")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_job_desc)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.comboBox_advisor = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_advisor.setObjectName("comboBox_advisor")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_advisor)
        self.dateEdit_s_date = QtWidgets.QDateEdit(self.frame_2)
        self.dateEdit_s_date.setCalendarPopup(True)
        self.dateEdit_s_date.setObjectName("dateEdit_s_date")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit_s_date)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.input_dist = QtWidgets.QLineEdit(self.frame_4)
        self.input_dist.setObjectName("input_dist")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_dist)
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.input_damg = QtWidgets.QTextEdit(self.frame_4)
        self.input_damg.setObjectName("input_damg")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_damg)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(Dialog)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bt_ok = QtWidgets.QPushButton(self.frame_5)
        self.bt_ok.setObjectName("bt_ok")
        self.horizontalLayout_3.addWidget(self.bt_ok)
        self.bt_cancel = QtWidgets.QPushButton(self.frame_5)
        self.bt_cancel.setObjectName("bt_cancel")
        self.horizontalLayout_3.addWidget(self.bt_cancel)
        self.verticalLayout.addWidget(self.frame_5)

        self.retranslateUi(Dialog)
        self.comboBox_reg_no.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "CUSTOMER"))
        self.label.setText(_translate("Dialog", "Name"))
        self.label_3.setText(_translate("Dialog", "Address"))
        self.label_5.setText(_translate("Dialog", "Contact no"))
        self.groupBox_2.setTitle(_translate("Dialog", "VEHICLE"))
        self.label_2.setText(_translate("Dialog", "Registration no"))
        self.label_4.setText(_translate("Dialog", "Type"))
        self.label_6.setText(_translate("Dialog", "Model"))
        self.label_7.setText(_translate("Dialog", "Job Description"))
        self.label_10.setText(_translate("Dialog", "Service Date"))
        self.label_11.setText(_translate("Dialog", "Service Advisor"))
        self.dateEdit_s_date.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.label_8.setText(_translate("Dialog", "Distance"))
        self.label_9.setText(_translate("Dialog", "Damages"))
        self.bt_ok.setText(_translate("Dialog", "Add"))
        self.bt_cancel.setText(_translate("Dialog", "Cancel"))

