# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v_add.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(503, 348)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.label_customer = QtWidgets.QLabel(Dialog)
        self.label_customer.setObjectName("label_customer")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_customer)
        self.label_contect = QtWidgets.QLabel(Dialog)
        self.label_contect.setObjectName("label_contect")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_contect)
        self.input_v_contact = QtWidgets.QLineEdit(Dialog)
        self.input_v_contact.setEnabled(False)
        self.input_v_contact.setObjectName("input_v_contact")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_v_contact)
        self.label_id = QtWidgets.QLabel(Dialog)
        self.label_id.setObjectName("label_id")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_id)
        self.input_v_id = QtWidgets.QLineEdit(Dialog)
        self.input_v_id.setEnabled(False)
        self.input_v_id.setObjectName("input_v_id")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_v_id)
        self.label_reg_no = QtWidgets.QLabel(Dialog)
        self.label_reg_no.setObjectName("label_reg_no")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_reg_no)
        self.input_v_reg_no = QtWidgets.QLineEdit(Dialog)
        self.input_v_reg_no.setClearButtonEnabled(False)
        self.input_v_reg_no.setObjectName("input_v_reg_no")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.input_v_reg_no)
        self.label_company = QtWidgets.QLabel(Dialog)
        self.label_company.setObjectName("label_company")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_company)
        self.input_v_company = QtWidgets.QLineEdit(Dialog)
        self.input_v_company.setObjectName("input_v_company")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.input_v_company)
        self.label_model = QtWidgets.QLabel(Dialog)
        self.label_model.setObjectName("label_model")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_model)
        self.input_v_model = QtWidgets.QLineEdit(Dialog)
        self.input_v_model.setObjectName("input_v_model")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.input_v_model)
        self.label_type = QtWidgets.QLabel(Dialog)
        self.label_type.setObjectName("label_type")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_type)
        self.input_v_type = QtWidgets.QLineEdit(Dialog)
        self.input_v_type.setObjectName("input_v_type")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.input_v_type)
        self.label_transmission = QtWidgets.QLabel(Dialog)
        self.label_transmission.setObjectName("label_transmission")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_transmission)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_ok = QtWidgets.QPushButton(self.frame)
        self.bt_ok.setObjectName("bt_ok")
        self.horizontalLayout.addWidget(self.bt_ok)
        self.bt_cancel = QtWidgets.QPushButton(self.frame)
        self.bt_cancel.setObjectName("bt_cancel")
        self.horizontalLayout.addWidget(self.bt_cancel)
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rbt_v_manual = QtWidgets.QRadioButton(Dialog)
        self.rbt_v_manual.setObjectName("rbt_v_manual")
        self.horizontalLayout_2.addWidget(self.rbt_v_manual)
        self.rbt_v_auto = QtWidgets.QRadioButton(Dialog)
        self.rbt_v_auto.setObjectName("rbt_v_auto")
        self.horizontalLayout_2.addWidget(self.rbt_v_auto)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.input_c_name = QtWidgets.QLineEdit(Dialog)
        self.input_c_name.setObjectName("input_c_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_c_name)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_customer.setText(_translate("Dialog", "Customer"))
        self.label_contect.setText(_translate("Dialog", "Contact"))
        self.label_id.setText(_translate("Dialog", "Vehicle ID"))
        self.input_v_id.setText(_translate("Dialog", "AUTOMATIC"))
        self.label_reg_no.setText(_translate("Dialog", "Registration No"))
        self.label_company.setText(_translate("Dialog", "Company"))
        self.label_model.setText(_translate("Dialog", "Model"))
        self.label_type.setText(_translate("Dialog", "Type"))
        self.label_transmission.setText(_translate("Dialog", "Transmission"))
        self.bt_ok.setText(_translate("Dialog", "OK"))
        self.bt_cancel.setText(_translate("Dialog", "Cancel"))
        self.rbt_v_manual.setText(_translate("Dialog", "Automatic"))
        self.rbt_v_auto.setText(_translate("Dialog", "Manual"))

